name: Fetch Market Prices

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install required dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libnss3 \
            libgbm1 \
            libxshmfence1 \
            libatk1.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxdamage1 \
            libxrandr2 \
            libxcomposite1 \
            libxfixes3 \
            chromium-browser

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Scraper Dependencies
        run: npm install puppeteer

      - name: Run Scraper
        run: node scraper/scrape.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"

